"use client";

import { useState } from "react";

type CodeTab = "dump" | "manifest" | "schedule";
type SqlDialect = "sqlite" | "postgres" | "mysql";

export function HeroCodeCard() {
  const [activeTab, setActiveTab] = useState<CodeTab>("dump");
  const [dialect, setDialect] = useState<SqlDialect>("sqlite");
  const [copied, setCopied] = useState(false);

  const sqliteCode = `-- In-Process Streaming Backup: remote libSQL / Turso SQLite
-- Reconstructs DDL from sqlite_schema & preserves sqlite_sequence
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

CREATE TABLE "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "email" TEXT NOT NULL UNIQUE,
  "role" TEXT NOT NULL DEFAULT 'member',
  "created_at" TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

-- Preserve autoincrement sequence counter
INSERT INTO "sqlite_sequence" ("name", "seq") VALUES ('users', 4281);

-- Batched streaming insert
INSERT INTO "users" ("id", "email", "role", "created_at") VALUES
  (1, 'alice@example.com', 'admin', '2026-03-14 09:12:00'),
  (2, 'bob@example.com', 'member', '2026-03-14 09:15:30'),
  (3, 'carol@example.com', 'member', '2026-03-14 09:21:45');

CREATE INDEX "idx_users_email" ON "users" ("email");
COMMIT;`;

  const postgresCode = `-- In-Process Streaming Backup: PostgreSQL 16
-- Streamed on-the-fly through Gzip directly into S3
SET statement_timeout = 0;
SET client_encoding = 'UTF8';

CREATE TABLE public.orders (
  id bigint NOT NULL,
  customer_id uuid NOT NULL,
  total_cents integer NOT NULL,
  status character varying(32) DEFAULT 'pending'::character varying
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME public.orders_id_seq
  START WITH 1
  INCREMENT BY 1
);

INSERT INTO public.orders (id, customer_id, total_cents, status) VALUES
  (1001, '550e8400-e29b-41d4-a716-446655440000', 8950, 'fulfilled'),
  (1002, '550e8400-e29b-41d4-a716-446655440001', 14200, 'processing');`;

  const mysqlCode = `-- In-Process Streaming Backup: MySQL 8.0+
-- Streamed table definitions & batched inserts
SET FOREIGN_KEY_CHECKS = 0;
SET AUTOCOMMIT = 0;

DROP TABLE IF EXISTS \`audit_logs\`;
CREATE TABLE \`audit_logs\` (
  \`id\` bigint unsigned NOT NULL AUTO_INCREMENT,
  \`event\` varchar(64) NOT NULL,
  \`payload\` json DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOCK TABLES \`audit_logs\` WRITE;
INSERT INTO \`audit_logs\` (\`id\`, \`event\`, \`payload\`) VALUES
  (1, 'user.login', '{"ip": "172.20.0.1", "auth": "session"}'),
  (2, 'backup.dispatched', '{"engine": "mysql", "size": "4.2MB"}');
UNLOCK TABLES;
COMMIT;`;

  const manifestCode = `{
  "version": 1,
  "uncompressedSizeBytes": 3489120,
  "tables": [
    { "name": "users", "rowCount": 4281 },
    { "name": "orders", "rowCount": 18490 },
    { "name": "audit_logs", "rowCount": 84210 },
    { "name": "connections", "rowCount": 3 }
  ]
}`;

  const scheduleCode = `schedule_id: "sch_prod_daily_0200"
target_database: "production-sqlite-primary"
database_engine: "sqlite" # libSQL / Turso
cron_expression: "0 2 * * *" # Daily at 02:00
timezone: "America/New_York"
retention_count: 7 # Retains 7 most recent snapshots

destination:
  bucket: "db-backups"
  prefix: "backups/user_01/production-sqlite-primary/"
  storage_class: "S3_STANDARD"

status:
  last_run: "2026-09-22T02:00:00-04:00 (success • 1.2s)"
  next_run: "2026-09-23T02:00:00-04:00"`;

  const getCurrentText = () => {
    if (activeTab === "dump") {
      if (dialect === "sqlite") return sqliteCode;
      if (dialect === "postgres") return postgresCode;
      return mysqlCode;
    }
    if (activeTab === "manifest") return manifestCode;
    return scheduleCode;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCurrentText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="overflow-hidden rounded-xl border border-hairline/20 bg-surface-dark text-on-dark shadow-xl">
      {/* Code Window Top Bar */}
      <div className="flex flex-wrap items-center justify-between border-b border-surface-dark-elevated bg-surface-dark-soft px-4 py-2.5 gap-2">
        {/* Window Traffic Lights & Tab Switcher */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5">
            <div className="h-2.5 w-2.5 rounded-full bg-[#ef4444]/80" />
            <div className="h-2.5 w-2.5 rounded-full bg-[#f59e0b]/80" />
            <div className="h-2.5 w-2.5 rounded-full bg-[#10b981]/80" />
          </div>

          <div className="flex items-center gap-1 rounded-md bg-surface-dark-elevated p-0.5 text-xs font-mono">
            <button
              type="button"
              onClick={() => setActiveTab("dump")}
              className={`rounded px-2.5 py-1 transition ${
                activeTab === "dump"
                  ? "bg-primary text-on-primary font-medium"
                  : "text-on-dark-soft hover:text-on-dark"
              }`}
            >
              SQL Dump
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("manifest")}
              className={`rounded px-2.5 py-1 transition ${
                activeTab === "manifest"
                  ? "bg-primary text-on-primary font-medium"
                  : "text-on-dark-soft hover:text-on-dark"
              }`}
            >
              .manifest.json
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("schedule")}
              className={`rounded px-2.5 py-1 transition ${
                activeTab === "schedule"
                  ? "bg-primary text-on-primary font-medium"
                  : "text-on-dark-soft hover:text-on-dark"
              }`}
            >
              Cron Schedule
            </button>
          </div>
        </div>

        {/* Copy Button */}
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1 rounded border border-surface-dark-elevated bg-surface-dark px-2 py-1 text-[11px] font-mono text-on-dark-soft transition hover:text-on-dark hover:border-hairline/40"
          >
            {copied ? (
              <>
                <svg className="h-3 w-3 text-success" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
                <span>Copied</span>
              </>
            ) : (
              <>
                <svg className="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
                <span>Copy</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Secondary Bar: Dialect Switcher when on SQL Dump tab */}
      {activeTab === "dump" && (
        <div className="flex items-center justify-between border-b border-surface-dark-elevated/60 bg-surface-dark px-4 py-1.5 text-xs">
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-mono text-on-dark-soft">Dialect:</span>
            <div className="flex items-center gap-1">
              <button
                type="button"
                onClick={() => setDialect("sqlite")}
                className={`rounded px-2 py-0.5 text-[11px] font-mono transition ${
                  dialect === "sqlite"
                    ? "bg-surface-dark-elevated text-accent-amber font-semibold border border-accent-amber/30"
                    : "text-on-dark-soft hover:text-on-dark"
                }`}
              >
                SQLite / libSQL
              </button>
              <button
                type="button"
                onClick={() => setDialect("postgres")}
                className={`rounded px-2 py-0.5 text-[11px] font-mono transition ${
                  dialect === "postgres"
                    ? "bg-surface-dark-elevated text-accent-teal font-semibold border border-accent-teal/30"
                    : "text-on-dark-soft hover:text-on-dark"
                }`}
              >
                PostgreSQL
              </button>
              <button
                type="button"
                onClick={() => setDialect("mysql")}
                className={`rounded px-2 py-0.5 text-[11px] font-mono transition ${
                  dialect === "mysql"
                    ? "bg-surface-dark-elevated text-primary font-semibold border border-primary/30"
                    : "text-on-dark-soft hover:text-on-dark"
                }`}
              >
                MySQL
              </button>
            </div>
          </div>

          <span className="hidden sm:inline-block font-mono text-[10px] text-on-dark-soft">
            Direct Gzip Stream → S3
          </span>
        </div>
      )}

      {/* Code Area */}
      <div className="p-4 overflow-x-auto bg-surface-dark-soft text-xs font-mono leading-relaxed">
        <pre className="text-on-dark">
          <code>{getCurrentText()}</code>
        </pre>
      </div>

      {/* Context Bar */}
      <div className="flex items-center justify-between border-t border-surface-dark-elevated/60 bg-surface-dark px-4 py-2 text-[11px] font-mono text-on-dark-soft">
        <div className="flex items-center gap-2">
          <span className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />
          <span>
            {activeTab === "dump"
              ? "Zero temporary disk files • Memory-bounded streaming"
              : activeTab === "manifest"
              ? "Companion sidecar for instant schema inspection"
              : "In-process cron worker • Automatic retention pruning"}
          </span>
        </div>
        <span className="hidden sm:inline text-hairline/40">AES-256-GCM</span>
      </div>
    </div>
  );
}
